name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Set to the desired version you want to use
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox  # This installs tox
          pip install scikit-learn  # This installs scikit-learn
          pip install pandas  # This installs pandas
          pip install numpy  # This installs numpy
          pip install joblib  # This installs joblib

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: tox # This will run the tests

  deploy_job:
    runs-on: ubuntu-latest
    needs: test_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy model
        run: tox -e deploy # This will run the deployment