name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: tox # This will run the tests

  deploy_job:
    runs-on: ubuntu-latest
    needs: test_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy model
        run: tox -e deploy # This will run the deployment